#!/bin/sh
#PBS -N analise
#PBS -e analise.err
#PBS -o analise.o
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=48:00:00


export I_MPI_FABRICS=shm
export OMP_NUM_THREADS=1

source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
source /opt/intel/impi/2019.6.166/intel64/bin/mpivars.sh
source /opt/intel/mkl/bin/mklvars.sh intel64

source /dados/softwares/gromacs-2018-3-source-mpi-mkl/bin/GMXRC.bash


cd $PBS_O_WORKDIR
#gmx_mpi grompp -f nvt.mdp -c confout.gro -p field.top

#mpirun -machinefile $PBS_NODEFILE -n 1  gmx_mpi grompp -f nvt.mdp -c confout.gro -p field.top


#/home/rafagp/exe/gromacs-5.1.4/build/bin/gmx grompp -f nvt.mdp -c confout.gro -p field.top
/home/rafagp/exe/gromacs-5.1.4/build/bin/gmx energy -nice 0 -b 5000 -o excesso<<+
15
20
21
23
+ 
