#!/bin/sh
#PBS -N GPU-rt1
#PBS -e GPU-rt1.err
#PBS -o GPU-rt1.o
#PBS -q gpuq
#  PBS -l select=1:ncpus=16:mpiprocs=8:ompthreads=2:ngpus=1
#PBS -l select=1:ncpus=8:mpiprocs=4:ompthreads=2:ngpus=1
#PBS -l walltime=48:00:00


export I_MPI_FABRICS=shm

source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
source /opt/intel/impi/2019.6.166/intel64/bin/mpivars.sh
source /opt/intel/mkl/bin/mklvars.sh intel64

source /opt/intel/bin/compilervars.sh intel64

source  /dados/softwares/gromacs-gpu/bin/GMXRC.bash


cd $PBS_O_WORKDIR

#mpirun -machinefile $PBS_NODEFILE -n 8  gmx_mpi mdrun -ntomp 2
/home/rafagp/exe/gromacs-5.1.4/build/bin/gmx mdrun
