#!/bin/sh
#PBS -N XXXXXXXX
#PBS -e error.err
#PBS -o output.o
#PBS -q workq 
#PBS -l nodes=1:ppn=20
#PBS -l walltime=48:00:00
### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M wirttipereira@hotmail.com

export I_MPI_FABRICS=shm
export OMP_NUM_THREADS=1

source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
source /opt/intel/impi/2019.6.166/intel64/bin/mpivars.sh
source /opt/intel/mkl/bin/mklvars.sh intel64

source /dados/softwares/gromacs-2018-3-source-mpi-mkl/bin/GMXRC.bash


cd $PBS_O_WORKDIR
#gmx_mpi grompp -f nvt.mdp -c confout.gro -p field.top

#mpirun -machinefile $PBS_NODEFILE -n 1  gmx_mpi grompp -f nvt.mdp -c confout.gro -p field.top


#/home/rafagp/exe/gromacs-5.1.4/build/bin/gmx grompp -f nvt.mdp -c confout.gro -p field.top
/home/rafagp/exe/gromacs-5.1.4/build/bin/gmx mdrun -nt 20
#/home/rafagp/exe/gromacs-5.1.4/build/bin/gmx mdrun -s topol.tpr -cpi state.cpt -nt 20
