#!/bin/sh
#PBS -N visc-x25ma
#PBS -e visc-x25-maginn-nvt5M.err
#PBS -o visc-x25-maginn-nvt5M.o
#PBS -q workq 
#PBS -l nodes=1:ppn=20
#PBS -l walltime=48:00:00


export I_MPI_FABRICS=shm
export OMP_NUM_THREADS=1

source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
source /opt/intel/impi/2019.6.166/intel64/bin/mpivars.sh
source /opt/intel/mkl/bin/mklvars.sh intel64

source /dados/softwares/gromacs-2018-3-source-mpi-mkl/bin/GMXRC.bash


cd $PBS_O_WORKDIR

sh roda-single.sh

